### ISSUE TITLE
Exit on Mode change with (F1/F2/F3)

### ISSUE THREAD

**Issue by cpfaff** [GeorgeFilipkin/pulsemixer#19]
I am on arch and use the latest version of pulsemixer from the aur repository. When I start it in interactive mode I cannot switch modes using the F keys. Pulsemixer then just exits.

**Comment by GeorgeFilipkin** [comment]
Most likely your terminal sends incorrect key-sequence which isn't picked up by ncurses as F1-3. The cause is, again most likely, is this: https://wiki.archlinux.org/index.php/Home_and_End_keys_not_working#TERM

If that's the case you should fix your $TERM variable since it will cause issues with many console applications. For naked tty you should use 'linux', for xterm and urxvt the fix is in the archwiki, as for the rest of GUI terminals you should consult their settings. And if you are guessing $TERM in .basrc/.zshrc, make sure you've guessed correctly. Completely removing any `export TERM` is also a viable option which allows your terminal emulator to set the variable to whatever value it can support.

But if that's not the case let me know and we'll dig deeper.

**Comment by cpfaff** [comment]
He. Perfect. That was the issue. I had set the term value vor various locations and for different applications and finally the value I set in my zshrc was the issue. Now it works as expected. Thanks
