### ISSUE TITLE
Context menu item not highlighted

### ISSUE THREAD

**Issue by tigerjack** [GeorgeFilipkin/pulsemixer#24]
When I press Enter to select one of the available options from the context menu, I can't see the highlighted option at all (see the first image below). I think that maybe it is due to my terminal colors, because it works well on a simple tty. 
However, many other curses-based tools I use have not this problem. The second image, for example, is taken from wicd-curses.
Is it possible to change the highlighted item style in some way? 

![image](https://user-images.githubusercontent.com/8199216/30515462-64313f6a-9b28-11e7-9bd9-a31139e36b18.png)

![image](https://user-images.githubusercontent.com/8199216/30515489-e4c8d2fa-9b28-11e7-8ae6-98b623f78592.png)

**Comment by GeorgeFilipkin** [comment]
Pulsemixer uses bold text to highlight selected item in context menu. Likely your terminal emulator doesn't allow bold. 

5b78f57 commit adds an arrow to better indicate selected item. Since pulsemixer is already heavy with color I'm somewhat reluctant to do background highlighting like wicd does. So, a simple arrow instead.

**Comment by tigerjack** [comment]
Thanks a lot, I'll wait for the updated package on the AUR. In the meantime, I've enabled the bold fonts in urxvt.
