### ISSUE TITLE
Bar-on character not displaying properly

### ISSUE THREAD

**Issue by sleao** [GeorgeFilipkin/pulsemixer#46]
I can't figure this one out on my own. I use the default config, which includes ▮ as the symbol for bar on. For some reason tho, it won't display on my terminal. It's just a blank space and I can't figure out what is going on with it. [This](https://imgur.com/Tvcf379) is what it looks like.

**Comment by GeorgeFilipkin** [comment]
Well, this is the first time I'm seeing something like this. Usually curses at least attempts to render that symbol (even if it messes up the output)

What you can try is:

- Check the `PULSEMIXER_BAR_STYLE` environment variable. It was used previously to change pulsemixer's appearance, maybe you still have it in your bashrc or something
- Remove config completely
- Try different terminal fonts, maybe yours is missing that symbol
- Try different terminal, preferably not vte-based, since they all tend to have the same bugs
- Create new config with `pulsemixer --create-config`, uncomment `bar-on` and set it to any normal ascii character to see if it will be rendered

This should help pinpoint the problem.

**Comment by sleao** [comment]
I've done a few of those things before. 

-  First, I don't think it's the terminal font, since I use vim to edit the config and I can see the character there (which I guess would mean it works)
- I tried to remove and redo the config a few times before asking, so I'm guessing that doesn't work too
- Also tried a few terminals, terminator, xterm, alacritty, kitty and a few other that I don't recall the name
- Didn't try to check the env variable, so I guess that's one thing I'll try as soon as I get home.

Just to be sure, could this be something that I've done or forgotten to do in my pc configs, since I'm running Arch and everything should be installed by hand?

**Comment by GeorgeFilipkin** [comment]
>I use vim to edit the config and I can see the character there

One other thing I can think of is some sort of ncurses problem. As far as I know vim doesn't use ncurses so this might be the reason why vim can render that symbol but pulsemixer cant. 

I also noticed that your screenshot doesn't have brackets and focus arrows around the volume bars (assuming you didn't disable them in config), so it's not only `bar-on` problem.

Here is a simple python test. See if it can print all the symbols:
```python
from curses import wrapper

def main(stdscr):
    stdscr.addstr(0, 0, '▮┌╶┐╴└┘─')
    stdscr.refresh()
    stdscr.getkey()

wrapper(main)
```

**Comment by sleao** [comment]
All blank on that, so I'm guessing whatever you think it is, you guessed it right.

**Comment by GeorgeFilipkin** [comment]
Any news?

**Comment by sleao** [comment]
Totally forgot to update you. I'm afraid I couldn't find anything related to it. I have no idea what's going on with my PC.

**Comment by sleao** [comment]
I'll close this issue, I'm back at Windows on my main PC right now. I'll install arch on my notebook and then use pulsemixer there. Thanks for the help, my man!
